STOP_WORDS_FR = [
    "a", "à", "â", "abord", "afin", "ah", "ai", "aie", "ainsi", "allaient",
    "allo", "allô", "allons", "après", "assez", "attendu", "au", "aucun",
    "aucune", "aujourd", "aujourd'hui", "auquel", "aura", "auront", "aussi",
    "autre", "autres", "aux", "auxquelles", "auxquels", "avaient", "avais",
    "avait", "avant", "avec", "avoir", "ayant", "b", "bah", "beaucoup", "bien",
    "bigre", "boum", "bravo", "brrr", "c", "ça", "car", "ce", "ceci", "cela",
    "celle", "celle-ci", "celle-là", "celles", "celles-ci", "celles-là", "celui",
    "celui-ci", "celui-là", "cent", "cependant", "certain", "certaine", "certaines",
    "certains", "certes", "ces", "cet", "cette", "ceux", "ceux-ci", "ceux-là",
    "chacun", "chacune", "chaque", "cher", "chers", "chez", "chiche", "chut",
    "ci", "cinq", "cinquantaine", "cinquante", "cinquantième", "cinquième",
    "clac", "clic", "combien", "comme", "comment", "compris", "concernant",
    "contre", "couic", "crac", "d", "da", "dans", "de", "debout", "dedans", "dehors",
    "delà", "depuis", "derrière", "des", "dès", "désormais", "desquelles",
    "desquels", "dessous", "dessus", "deux", "deuxième", "deuxièmement",
    "devant", "devers", "devra", "devrait", "différent", "différente",
    "différentes", "différents", "dire", "divers", "diverse", "diverses",
    "dix", "dix-huit", "dixième", "dix-neuf", "dix-sept", "doit", "doivent",
    "donc", "dont", "douze", "douzième", "dring", "du", "duquel", "durant",
    "e", "effet", "eh", "elle", "elle-même", "elles", "elles-mêmes", "en",
    "encore", "entre", "envers", "environ", "es", "ès", "est", "et", "etant",
    "étaient", "étais", "était", "étant", "etc", "été", "etre", "être",
    "eu", "euh", "eux", "eux-mêmes", "excepté","façon", "fais", "faisaient", "faisant", "fait", "faites", "fois", "font",
"force", "forces", "furent", "fus", "fut", "fûmes", "g", "gens", "h", "ha",
"haut", "hé", "hein", "hélas", "hem", "hep", "hi", "ho", "holà", "hop", "hormis",
"hors", "hou", "houp", "hue", "hui", "huit", "huitième", "hum", "hurrah", "i",
"ici", "il", "ils", "importe", "j", "je", "jusqu", "jusque", "juste", "k", "l",
"la", "là", "laquelle", "las", "le", "lequel", "les", "lès", "lesquelles",
"lesquels", "leur", "leurs", "longtemps", "lorsque", "lui", "lui-même", "m",
"ma", "maint", "maintenant", "mais", "malgré", "me", "même", "mêmes", "merci",
"mes", "mien", "mienne", "miennes", "miens", "mille", "mince", "mine", "moi",
"moi-même", "moins", "mon", "moyennant", "n", "na", "ne", "néanmoins", "neuf",
"neuvième", "ni", "nombreuses", "nombreux", "non", "nos", "notre", "nôtre",
"nôtres", "nous", "nous-mêmes", "nul", "o", "ô", "oh", "ohé", "ole", "olé",
"on", "ont", "onze", "onzième", "ore", "ou", "où", "ouf", "ouias", "oust", "ouste",
"outre", "p", "paf", "pan", "par", "parmi", "partant", "particulier",
"particulière", "particulièrement", "pas", "passé", "pendant", "personne",
"peu", "peut", "peuvent", "peux", "pff", "pfft", "pfut", "pif", "plein",
"plouf", "plus", "plusieurs", "plutôt", "pouah", "pour", "pourquoi", "premier",
"première", "premièrement", "près", "proche", "psitt", "puisque", "q", "qu",
"quand", "quant", "quanta", "quant-à-soi", "quarante", "quatorze", "quatre",
"quatre-vingt", "quatrième", "quatrièmement", "que", "quel", "quelconque",
"quelle", "quelles", "quelque", "quelques", "quelqu'un", "quels", "qui", "quiconque",
"quinze", "quoi", "quoique", "r", "revoici", "revoilà", "rien", "s", "sa",
"sacrebleu", "sans", "sapristi",
"sas", "se", "seize", "selon", "sept", "septième", "sera", "seront", "ses",
"seulement", "si", "sien", "sienne", "siennes", "siens", "sinon", "six",
"sixième", "soi", "soi-même", "soit", "soixante", "son", "sont", "sous",
"souvent", "soyez", "soyons", "stop", "suis", "suivant", "suite", "sur", "surtout",
"t", "ta", "tac", "tant", "te", "té", "tel", "telle", "tellement", "telles",
"tels", "tenant", "tes", "tic", "tien", "tienne", "tiennes", "tiens", "toi",
"toi-même", "ton", "tôt", "touchant", "toujours", "tous", "tout", "toute",
"toutes", "treize", "trente", "très", "trois", "troisième", "troisièmement",
"trop", "trouvez", "trouvons", "tu", "u", "un", "une", "unes", "uns", "v", "va",
"vais", "vas", "vé", "vers", "via", "vif", "vifs", "vingt", "vivat", "vive",
"vives", "vlan", "voici", "voilà", "vont", "vos", "votre", "vôtre", "vôtres",
"vous", "vous-mêmes", "vu", "w", "x", "y", "z", "zut"
]

STOP_WORDS_EN = [
    'a', 'about', 'above', 'after', 'again', 'against', 'all', 'am', 'an', 'and', 'any', 'are', 'aren\'t',
    'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by',
    'can', 'can\'t', 'cannot', 'could', 'couldn\'t',
    'did', 'didn\'t', 'do', 'does', 'doesn\'t', 'doing', 'don', 'don\'t', 'down', 'during',
    'each',
    'few', 'for', 'from', 'further',
    'had', 'hadn\'t', 'has', 'hasn\'t', 'have', 'haven\'t', 'having', 'he', 'he\'d', 'he\'ll', 'he\'s', 'her', 'here',
    'here\'s', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'how\'s',
    'i', 'i\'d', 'i\'ll', 'i\'m', 'i\'ve', 'if', 'in', 'into', 'is', 'isn\'t', 'it', 'it\'s', 'its', 'itself',
    'let\'s',
    'me', 'more', 'most', 'mustn\'t', 'my', 'myself',
    'no', 'nor', 'not', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'ought', 'our', 'ours', 'ourselves', 'out', 'over', 'own',
    'same', 'shan\'t', 'she', 'she\'d', 'she\'ll', 'she\'s', 'should', 'shouldn\'t', 'so', 'some', 'such',
    'than', 'that', 'that\'s', 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'there\'s', 'these', 'they', 'they\'d', 'they\'ll', 'they\'re', 'they\'ve', 'this', 'those', 'through', 'to', 'too',
    'under', 'until', 'up',
    'very',
    'was', 'wasn\'t', 'we', 'we\'d', 'we\'ll', 'we\'re', 'we\'ve', 'were', 'weren\'t', 'what', 'what\'s', 'when', 'when\'s', 'where', 'where\'s', 'which', 'while', 'who', 'who\'s', 'whom', 'why', 'why\'s', 'with', 'won\'t', 'would', 'wouldn\'t',
    'you', 'you\'d', 'you\'ll', 'you\'re', 'you\'ve', 'your', 'yours', 'yourself', 'yourselves'
    # Ajoutez d'autres mots si nécessaire
]
